### ISSUE TITLE
error: proxy -u http://192.168.1.2:8000/ -l 90 -a 192.168.1.1 -r 80 -n

### ISSUE THREAD

**Issue by Berlimdev** [SECFORCE/Tunna#13]
>proxy -u http://192.168.1.2:8000/ -l 90 -a 192.168.1.1 -r 80 -n 
<pre>
  _____
 |_   _|   _ _ __  _ __   __ _
   | || | | | '_ \| '_ \ / _` |
   | || |_| | | | | | | | (_| |
   |_| \__,_|_| |_|_| |_|\__,_|

Tunna v1.1a, for HTTP tunneling TCP connections by Nikos Vassakis
http://www.secforce.com / nikos.vassakis <at> secforce.com
###############################################################

[+] Spawning keep-alive thread
[-] Keep-alive thread not required
[+] Checking for proxy: False
[T] Connected To Socks:  ('192.168.1.2', 51509)
[+] Starting Ping thread
General Exception: [Errno 9] Bad file descriptor
[Server] Closing the connection
[-] Disconnected
</pre>
>Why does this error occur?  [Errno 9] Bad file descriptor

![image](https://user-images.githubusercontent.com/31291125/32052828-26d7297a-ba38-11e7-8a1a-b31b4fc19b55.png)

**Comment by GlaucioAlmeida** [comment]
> proxy -u http://192.168.1.2:8000/ -l 90 -a 192.168.1.1 -r 80 -b 1024 -n
<pre>
###############################################################

[+] Spawning keep-alive thread
[-] Keep-alive thread not required
[+] Checking for proxy: False
[T] Connected To Socks:  ('192.168.1.2', 51794)
[+] Starting Ping thread
[-] Client Disconnected
[!] Received Interrupt or Something Went Wrong
[Server] Closing the connection
[-] Disconnected
[Server] No open socket
[-] Disconnected
</pre>

**Comment by nvssks** [comment]
Could you explain a bit more what are you trying to do?
Are you running python on OpenWRT? What kind of host do you have?

**Comment by GlaucioAlmeida** [comment]
I am running Webserver.exe and proxy.exe.
I am redirecting my router (192.168.1.1:80) to (192.168.1.2:90) only to test the Tunna.
The ip of my computer is 192.168.1.2
The ip of Webserver.exe is 192.168.1.2:8000

**Comment by nvssks** [comment]
Do you get any errors on the webserver?

Also why don't you try without the -n (and without -a -r ) options and by setting 192.168.1.2:8000 as a socks4a proxy in the browser?

**Comment by GlaucioAlmeida** [comment]
No error message occurs in the webserver.
Without -n, -a and -r does not work the way I want it.
I'm trying to redirect traffic, like ngrok or pagekite.
The Tunna can do that?

**Comment by nvssks** [comment]
I'll look into this - the binary version hasn't been updated in a while.

If you just want to do port forwarding to a remote host, why don't you use something simpler like:
netsh in windows, eg:
netsh interface portproxy add v4tov4 listenport=<lport>
listenaddress=<lhost> connectport=<rport> connectaddress=<rhost>

**Comment by GlaucioAlmeida** [comment]
Nice! I'll test it directly on ".py" to see if it works.

I do not use "netsh" because I want to break barriers like the firewall and the router.
I tested "Tunna" on my localhost, but it was just a test!

The internet provider does not allow open ip:port on the extranet.
My extranet ip is the ip of the router mikrotik of the provider.
I thought Tunna was the same as ngrok.
